# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'Marcel Goh'
# tagline:        ''
description:      'A Math/CS and Linguistics student at McGill University'
# url:            https://marcelgoh.github.io

# baseurl:        https://marcelgoh.github.io

author:
  name:           'Marcel Goh'
  url:            'https://marcelgoh.github.io'
  email:          'marcel.goh@mail.mcgill.ca'
  github:         'https://github.com/marcelgoh'
  instagram:      'https://www.instagram.com/marcelgoh'
  facebook:       'https://www.facebook.com/marcel.goh.1'
  linkedin:       'https://www.linkedin.com/in/marcel-goh-463ba2149'


paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

defaults:
    scope:
      path: ""        # empty string for all files
      type: post     # limit to posts
    values:
      is_post: true   # automatically set is_post=true for posts

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/marcelgoh

future: true

include: ['.htaccess']
